export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'
export const SET_EMAIL= 'SET_EMAIL'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
